### ISSUE TITLE
jmx monitoring - integrate prometheus PodMonitor objects to the chart

### ISSUE THREAD

**Issue by pmauduit** [camptocamp/helm-georchestra#4]
During the first implementation of the jmx probe monitoring into the chart, it was not necessary to have extra k8s objects to make prometheus scrape the metrics. We now need some extra objects like podmonitors / servicemonitor and so on.

On DataGrandEst, we created this objects outside of the chart, but we might want to integrate them here, where it will be more relevant. Here is an example of spec (for GeoNetwork):

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    argocd.argoproj.io/instance: datagrandest-dev-k8s-extra # to be changed obviously
    org.georchestra.service/name: georchestra-geonetwork
  name: georchestra-geonetwork
  namespace: datagrandest-dev
spec:
  podMetricsEndpoints:
    - port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/component: georchestra-geonetwork
      app.kubernetes.io/instance: georchestra
      app.kubernetes.io/name: georchestra
      org.georchestra.service/name: georchestra-geonetwork


```
